name: flutter_box_transform
description: A Flutter implementation of box_transform package that provides easy 2D box transform operations with advanced resizing of rect in UI.

version: 0.4.0

repository: https://github.com/hyper-designed/box_transform
homepage: https://github.com/hyper-designed/box_transform
issue_tracker: https://github.com/hyper-designed/box_transform/issues
documentation: https://docs.page/hyper-designed/box_transform

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  box_transform: ^0.4.0
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
