name: example
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  adaptive_theme: ^3.2.0
  url_launcher: ^6.1.10
  provider: ^6.0.5
  equatable: ^2.0.5
  dart_style: ^2.3.0
  vector_math: ^2.1.4
  file_picker: ^5.2.11
  flutter_box_transform:
    path: ../
  box_transform:
    path: ../../box_transform

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/ic_flip.png
    - assets/images/image1.jpg
    - assets/images/image2.jpg
    - assets/images/image3.jpg
    - assets/images/image4.jpg
    - assets/images/image5.jpg
    - assets/images/image6.jpg
    - assets/images/image7.jpg
    - assets/images/image8.jpg
    - assets/images/image9.jpg
    - assets/images/image10.jpg