name: box_transform
description: A pure dart implementation of advanced 2D box transformation with easy and simple API.

version: 0.2.1

repository: https://github.com/hyper-designed/box_transform
homepage: https://github.com/hyper-designed/box_transform
issue_tracker: https://github.com/hyper-designed/box_transform/issues
documentation: https://docs.page/hyper-designed/box_transform

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  vector_math: ^2.1.4
  meta: ^1.8.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.2
  coverage: ^1.6.3
