name: Build

on:
  push:
    paths:
      - '**.dart'
      - '**.yaml'
      - '**.yml'
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - name: Install Melos
        run: flutter pub global activate melos
      - name: Setup Melos
        run: melos bootstrap
      - name: Get Dependencies
        run: melos deps
      - name: Build Example
        run: |
          cd packages/flutter_box_transform/example
          flutter build web --release
      - name: Deploy example
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_BOX_TRANSFORM_EXAMPLE }}'
          channelId: live
          projectId: box-transform-example
          target: example
      - name: Build Playground
        run: |
          cd packages/flutter_box_transform/playground
          flutter build web --release
      - name: Deploy playground
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_BOX_TRANSFORM_EXAMPLE }}'
          channelId: live
          projectId: box-transform-example
          target: playground
